### ISSUE TITLE
Feature request: Add support for YankStack :Yanks command

### ISSUE THREAD

**Issue by mtglsk** [dahu/vim-lotr#5]
Would be cool to be able to see recent yanks as reported by the `:Yanks` command of YankStack plugin.

**Comment by dahu** [comment]
Added in 2af02c3d296d3e5661ef2a2f010a7f985825688f

**Comment by mtglsk** [comment]
Thanks!

**Comment by dahu** [comment]
You're welcome. I've never used YankStack, but it was easy enough to
support.
